# Generated by Django 4.2 on 2023-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="location",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="yelp_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
