services:
- type: web
  name: placesmemo
  env: python
  buildCommand: "./build.sh"
  startCommand: "gunicorn placesmemo.wsgi:application"
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: placesmemo
        property: connectionString
    - key: SECRET_KEY
      generateValue: true
    - key: WEB_CONCURRENCY
      value: 4

databases:
- name: placesmemo
  databaseName: placesmemo
  user: tjbredemeyer
