# Generated by Django 4.2 on 2023-04-22 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
        ('tags', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creted_at', models.TimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lists', models.ManyToManyField(related_name='memos', to='lists.list')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='places.place')),
                ('tags', models.ManyToManyField(related_name='memos', to='tags.tag')),
            ],
        ),
    ]
