# Generated by Django 4.2 on 2023-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_delete_taggedmemo'),
        ('lists', '0002_list_created_at'),
        ('memos', '0003_alter_memo_lists_alter_memo_place_alter_memo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='lists',
            field=models.ManyToManyField(blank=True, to='lists.list'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
