# Generated by Django 4.2 on 2023-04-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaggedMemo',
        ),
    ]
