# Generated by Django 4.2 on 2023-04-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
